### ISSUE TITLE
Finaaliversion TODO

### ISSUE THREAD

**Issue by mikahimself** [TeamRommel/RollingRommel#13]
- [ ] Viimeistele autojen AI
- [ ] Viimeistele päävalikko
- [ ] Lisää introon tarina
- [ ] Lisää all6464.png-kuvaan aidat kohtiin, joista ei pääse läpi
- [ ] Lisää Cup-kisaan pistelasku
- [ ] Lisää ampumismekanismi
- [ ] Lisää Cup-kisaan Final Results -ruutu
